fix for `npm run build`
was crashing on netlify because svelte kit doesn't like tailwind custom classes that @apply other classes from another file when building for prod

console output:

```cmd
C:\Users\justi\Documents\GitHub\colorpicker>npm run build

> color-convert@1.0.0 build
> svelte-kit build

vite v2.6.11 building for production...
transforming (3) src\routes\__layout.svelte
warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
✓ 14 modules transformed.
[vite-plugin-svelte] C:/Users/justi/Documents/GitHub/colorpicker/src/routes/index.svelte:3:3: The `surface` class does not exist. If `surface` is a custom class, make
sure it is defined within a `@layer` directive.
file: C:/Users/justi/Documents/GitHub/colorpicker/src/routes/index.svelte
> C:/Users/justi/Documents/GitHub/colorpicker/src/routes/index.svelte:3:3: The `surface` class does not exist. If `surface` is a custom class, make sure it is defined
within a `@layer` directive.
CssSyntaxError: C:/Users/justi/Documents/GitHub/colorpicker/src/routes/index.svelte:3:3: The `surface` class does not exist. If `surface` is a custom class, make sure
it is defined within a `@layer` directive.
    at Input.error (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\postcss\lib\input.js:123:16)
    at AtRule.error (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\postcss\lib\node.js:60:32)
    at processApply (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\tailwindcss\lib\jit\lib\expandApplyAtRules.js:172:23)
    at C:\Users\justi\Documents\GitHub\colorpicker\node_modules\tailwindcss\lib\jit\lib\expandApplyAtRules.js:229:5
    at C:\Users\justi\Documents\GitHub\colorpicker\node_modules\tailwindcss\lib\jit\processTailwindFeatures.js:61:46
    at C:\Users\justi\Documents\GitHub\colorpicker\node_modules\tailwindcss\lib\jit\index.js:25:56
    at LazyResult.runOnRoot (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\postcss\lib\lazy-result.js:339:16)
    at LazyResult.runAsync (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\postcss\lib\lazy-result.js:391:26)
    at async process (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\svelte-preprocess\dist\transformers\postcss.js:28:36)
    at async style (C:\Users\justi\Documents\GitHub\colorpicker\node_modules\svelte-preprocess\dist\autoProcess.js:180:37)
```